In [ ]:
#Practice1

#Q1
import numpy as np

#Q2
# 배열 만들기
arr= np.array([10,11,12,13,14,15])

# 확인
print(arr)

# 정보 확인
print(arr.ndim)
print(arr.shape)
print(arr.dtype)

#Q3
a = [[11, 12, 13, 14], [15, 16, 17, 18], [19, 20, 21, 22]]

# 배열 만들기
arr2= np.array(a)

# 확인
print(arr2)

# 정보 확인
print(arr2.ndim)
print(arr2.shape)
print(arr2.dtype)
##################################################
#Q1
# 배열 만들기
a = np.array([[11, 12, 13, 14], 
              [15, 16, 17, 18], 
              [19, 20, 21, 22]])

# 배열 형태 확인
print(a.shape)


# (4, ?))형태의 2차원 배열
b=np.reshape(a,(4,-1))
print(b)
print(b.shape)

# (2, ?) 형태의 2차원 배열
c=a.reshape(2,-1)
print(c)
print(c.shape)
#################################################
a = np.array([[11, 12, 13, 14], 
              [15, 16, 17, 18], 
              [19, 20, 21, 22]])
#Q1
a[0:3,1:2]
#Q2
a[1:3,1:3]
#################################################
score = np.array([[78, 91, 84, 89, 93, 65],
                 [82, 87, 96, 79, 91, 73]])
#Q1
print(score[score<80])
#Q2
condition= score%2==0
print(score[condition])
#################################################
#종합실습
# 라이브러리 불러오기
import numpy as np
# [[  1  2  3]
#  [  4  5  6]
#  [  7  8  9]
#  [ 10 11 12]]
a=list(range(1,13))

np_arr= np.reshape(a,(4,3))
np_arr

np_arr.shape

np_02=np_arr.reshape(3,4)
np_02

np_arr[2,:]

print(np_arr*10)

np_arr[np_arr>7]

np_arr[np_arr>7]=np_arr[np_arr>7]*2

np_arr

np_bool=np.where(np_arr%3==0,1,0)
np_bool

print(np.mean(np_arr))
print(np.mean(np_arr,0))
print(np.mean(np_arr,1))
